// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TestVnPay.Models;

public partial class TestVnPayContext : DbContext
{
    public TestVnPayContext(DbContextOptions<TestVnPayContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Payments> Payments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Payments>(entity =>
        {
            entity.ToTable("Payment");

            entity.HasKey(e => e.PaymentId);
            entity.Property(e => e.PaymentId).ValueGeneratedOnAdd();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.ExpireDate).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy).HasMaxLength(50);
            entity.Property(e => e.MerchantId).HasMaxLength(50);
            entity.Property(e => e.PaidAmount).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.PaymentContent).HasMaxLength(250);
            entity.Property(e => e.PaymentCurrency).HasMaxLength(10);
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentDestinationId).HasMaxLength(50);
            entity.Property(e => e.PaymentLanguage).HasMaxLength(10);
            entity.Property(e => e.PaymentLastMessage).HasMaxLength(250);
            entity.Property(e => e.PaymentRefId).HasMaxLength(50);
            entity.Property(e => e.PaymentStatus).HasMaxLength(20);
            entity.Property(e => e.RequiredAmount).HasColumnType("decimal(19, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}